
[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"

[bans]
multiple-versions = "deny"
deny = []
skip = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []

[licenses]
allow-osi-fsf-free = "both"
copyleft = "deny"
confidence-threshold = 0.95
allow = [
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
]

#TODO @mark: temporary
[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]
